### ISSUE TITLE
[grayskull 150] tt-smi returns error

### ISSUE THREAD

**Issue by GQsj** [tenstorrent/tt-smi#53]
After inserting the card in PCI-3(instead of PCI-4 at this moment), and install the list software, I am getting error like below:
```
(py3810) root@hello:~# tt-smi --list
 Detected Chips: 1
 Detecting ARC: /
 Detecting DRAM: /
 [] ETH: /
Gathering Information ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--
Traceback (most recent call last):
  File "/root/miniconda3/envs/py3810/bin/tt-smi", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/py3810/lib/python3.8/site-packages/tt_smi/tt_smi.py", line 788, in main
    backend = TTSMIBackend(devices)
  File "/root/miniconda3/envs/py3810/lib/python3.8/site-packages/tt_smi/tt_smi_backend.py", line 79, in __init__
    self.smbus_telem_info.append(self.get_smbus_board_info(i))
  File "/root/miniconda3/envs/py3810/lib/python3.8/site-packages/tt_smi/tt_smi_backend.py", line 173, in get_smbus_board_info
    telem_struct = pylewen_chip.get_telemetry()
Exception: Message 43705 not recognized
   0: luwen_if::arc_msg::arc_msg
   1: luwen_if::chip::grayskull::Grayskull::get_telemetry_offset
   2: once_cell::imp::OnceCell<T>::initialize::{{closure}}
```
How should I fix it? is there any way to check the card installed and working normally?

the platform I tried:
1. ubuntu 20.04 and 22.04
2. tt-kmd 1.27.1 and 1.29 all tried Separately;
3. fw_pack-80.9.0.0.fwbundle and fw_pack-80.10.0.0.fwbundle all tried Separately;

p.s. In the fw_pack installation, the instruction hints me "If running this last command results in an error that says the firmware is too old, add the "--force" parament", but in this step, it already told me Message 43705 not recognized:
```
Stage: FLASH
Sub stage: VERIFYfw-package can be flashed: completeVerifyingVerifying Grayskull[o] can be flashed.
Stage: FLASH
Sub stage FLASH step 1:Grayskull[o]
Hit error Message 43705 not recognized
while trying to determine running firmware, Falling back to assuming that it needs an update
Looks like you are running a very old set of fw, assuming that it needs an update
Now flashing tt-flash version:(80.9.0.0)
Forced RoM update reguested. RoM will now be updated.
```

**Comment by GQsj** [comment]
Solved. the "Above 4G Decoding" should be enabled in the system BIOS.
